import type { Metadata } from "next";
import { Roboto, DM_Mono, Inconsolata } from "next/font/google";
import "./globals.css";
import { Toaster } from "@/components/ui/sonner";
import OfflineOverlay from "@/components/defined/OfflineOverlay";

const roboto = Roboto({
  variable: "--font-roboto",
  subsets: ["latin"],
})
const dm_mono = Inconsolata({
  variable: "--font-dm-mono",

  subsets: ["latin"],
})

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${roboto.variable} ${dm_mono.variable} antialiased`}
      >
        {children}
        <OfflineOverlay />
        <Toaster />
      </body>
    </html>
  );
}
